/** @file
 *  @brief Base class providing unique hashed IDs from source_location.
 */

#pragma once

#include "element.hpp"
#include <cstdint>
#include <source_location>
#include <string_view>

namespace cppreact {
  namespace _detail {

    /** @brief Utility struct for FNV-1a hashing operations. */
    struct HashUtils {
      /// FNV-1a offset basis for 64-bit
      static constexpr uint64_t FNV_OFFSET_BASIS = 14695981039346656037ULL;
      /// FNV-1a prime for 64-bit
      static constexpr uint64_t FNV_PRIME = 1099511628211ULL;

      /** @brief Core FNV-1a hash over a raw byte sequence.
       *  @param data Pointer to the data to hash.
       *  @param size Number of bytes.
       *  @param seed Starting hash value.
       *  @return 64-bit hash.
       */
      static uint64_t hash_bytes(const void* data, size_t size, uint64_t seed = FNV_OFFSET_BASIS) {
          const unsigned char* bytes = static_cast<const unsigned char*>(data);
          uint64_t hash = seed;
          for (size_t i = 0; i < size; ++i) {
              hash ^= bytes[i];
              hash *= FNV_PRIME;
          }
          return hash;
      }

      /** @brief Combine a string_view into the hash. */
      static uint64_t hash_combine(uint64_t seed, std::string_view sv) {
          return hash_bytes(sv.data(), sv.size(), seed);
      }

      /** @brief Combine an integer value into the hash. */
      template <typename T>
      static uint64_t hash_combine(uint64_t seed, T value) {
          return hash_bytes(&value, sizeof(T), seed);
      }
    };

    /** @brief Base class providing a unique ID derived from source_location.
     *
     *  IDs are generated by hashing the file name, line, and column from
     *  the construction site, and may incorporate a parent ID.
     */
    class identifiable {
    private:
      std::source_location _loc; ///< Source location used for ID hashing
      uint64_t _id;             ///< Unique identifier
      bool _parent_set = false; ///< Whether a parent ID has been set
    protected:
      /** @brief Construct and compute the ID from the given source location. */
      identifiable(std::source_location loc) {
        _id = HashUtils::FNV_OFFSET_BASIS;
        _id = HashUtils::hash_combine(_id, std::string_view(loc.file_name()));
        _id = HashUtils::hash_combine(_id, loc.line());
        _id = HashUtils::hash_combine(_id, loc.column());
      }
    public:
      /** @brief Incorporate a parent ID into this element's ID. */
      void set_parent(identifiable* parent) {
        if (_parent_set) return;
        _id = HashUtils::hash_combine(_id, parent->id());
        _parent_set = true;
      }
      /** @brief Get the unique identifier. */
      uint64_t id() const {return _id;}
      virtual ~identifiable() {}
      /** @brief Get the underlying element reference. */
      virtual element& get() = 0;
    };
  }
}
